Add Image Process
qingstor/qingstor-sdk-go pull request #34
Opened 2017-08-14 03:18 UTC by zhaohuXing

2017-08-14 04:42 UTC, pengsrc requested changes

2017-08-14 04:42 UTC, pengsrc commented on helpers/image.go
> +
Import order is not tidy.

``` Go
import (
	"fmt"
	"reflect"
	"strings"

	"github.com/yunify/qingstor-sdk-go/service"
)
```

2017-08-14 04:42 UTC, pengsrc commented on helpers/image_test.go
> +
Import order is not tidy.

2017-08-14 04:42 UTC, pengsrc commented on test/main.go
> -
Why?

2017-08-16 06:10 UTC, Xuanwo requested changes

2017-08-16 06:10 UTC, Xuanwo commented on client/image.go
> +	name        *string
Use `objectKey` directly here.

2017-08-16 06:25 UTC, zhaohuXing commented on client/image.go
> +	name        *string
OK, Thanks.

2017-08-16 08:16 UTC, Xuanwo commented
Rebase your code from master.

2017-08-16 09:08 UTC, zhaohuXing commented
Done.

2017-08-17 07:29 UTC, pengsrc approved these changes

2017-08-17 07:32 UTC, Xuanwo approved these changes

2017-08-17 07:32 UTC, merged