Adding new-SDKs
qingstor/qingstor-sdk-go pull request #38
Opened 2017-08-25 10:27 UTC by sightseer

These are two methods of multipart uploading client.
File chunk method is to read each part of uploading file.
Uploading client method is to upload the whole file.

2017-08-25 13:09 UTC, sightseer commented
Updated 20180825,2110

2017-08-26 10:35 UTC, Xuanwo requested changes

2017-08-26 10:35 UTC, Xuanwo commented on client/upload_client.go
> +import (
import 要 follow 项目的规则，比如 request 中：

```go
import (
	"errors"
	"fmt"
	"net/http"
	"reflect"
	"strconv"
	"time"

	"github.com/pengsrc/go-shared/convert"

	"github.com/yunify/qingstor-sdk-go/logger"
	"github.com/yunify/qingstor-sdk-go/request/builder"
	"github.com/yunify/qingstor-sdk-go/request/data"
	"github.com/yunify/qingstor-sdk-go/request/signer"
	"github.com/yunify/qingstor-sdk-go/request/unpacker"
)
```

2017-08-26 10:35 UTC, Xuanwo commented on client/upload_client.go
> +func UploadClient(fd *os.File, objectKey string, partSize int, bucket *qs.Bucket) {
为什么是一个 func ？应该实现一个 struct ，然后实现这个 struct 的一个方法。

2017-08-26 10:35 UTC, Xuanwo commented on client/file_chunk.go
> +func ReadObjectPart(fd *os.File, partSize int) []byte {
先实现一个 struct，然后实现这个 struct 的方法，不要直接写一个 func

2017-08-26 10:35 UTC, Xuanwo commented on client/upload_client.go
> +		panic(completeErr)
要遵循项目的规范，go sdk 中出错不会直接 panic ，然后将 err return，交由上级逻辑来处理。可以参考： https://github.com/yunify/qingstor-sdk-go/blob/master/request/request.go#L104

2017-08-26 10:35 UTC, Xuanwo commented on client/upload_client.go
> +	output, initErr := bucket.InitiateMultipartUpload(
最好不要在一个函数中塞进去太多复杂的逻辑，考虑一下拆分

2017-08-26 10:35 UTC, Xuanwo commented on client/upload_client.go
> +		panic(initErr)
不要直接 panic，把 error return 会更好。

2017-08-26 10:35 UTC, Xuanwo commented on client/file_chunk.go
> +	return chunk[:lenBuf]
现在的实现会在内存中出现多次 copy，可以考虑参考一下 aws uploader 的实现： https://github.com/aws/aws-sdk-go/blob/master/service/s3/s3manager/upload.go#L507

2017-08-26 10:35 UTC, Xuanwo commented on client/upload_client.go
> +			panic(uploadErr)
不要直接 panic

2017-08-29 04:09 UTC, sightseer commented
Updated 20170828,1210

2017-08-29 04:57 UTC, Xuanwo requested changes

2017-08-29 04:57 UTC, Xuanwo commented on client/upload_client.go
> +type Uploader struct {
Follow the style like https://github.com/yunify/qingstor-sdk-go/blob/master/client/image/image.go#L99 , Upload is enough

2017-08-29 04:57 UTC, Xuanwo commented on client/upload_client.go
> +	Ubucket  *qs.Bucket
We will not expose the bucket, so just keep them private, ref: https://github.com/yunify/qingstor-sdk-go/blob/master/client/image/image.go#L99-L102

2017-08-29 04:57 UTC, Xuanwo commented on client/upload_client.go
> +	qs "github.com/yunify/qingstor-sdk-go/service"
service is unique in this package, we don't need to rename it to `qs`

2017-08-29 04:57 UTC, Xuanwo commented on client/upload_client.go
> +func (u *Uploader) UploadClient(fd *os.File, objectKey string) error {
In go, we use New or Init for create a new instance.

2017-08-29 04:57 UTC, Xuanwo commented on client/file_chunk.go
> +package client
use `upload` package will be better.

2017-08-29 04:57 UTC, Xuanwo commented on client/upload_client.go
> +package client
Put this file inot `client/upload` folder and use `upload` package.

2017-08-29 04:57 UTC, Xuanwo commented on client/upload_client.go
> +	objectReader.objectSize, _ = fd.Seek(0, io.SeekEnd)
With `NewSectionReader`, we don't need `objectSize`

2017-08-29 08:48 UTC, sightseer commented
Updated 20170829,1649

2017-08-29 13:57 UTC, sightseer commented
Add log, typeAssert method
Updated 20170829,2155

2017-08-30 05:51 UTC, sightseer commented
Updated 20170830,1352

2017-09-21 05:15 UTC, sightseer commented
Add file_chunk test file

2017-09-25 08:55 UTC, pengsrc commented
What's the progress of this pull request?

2017-09-25 09:15 UTC, sightseer commented
Add upload client test file

2017-09-25 10:10 UTC, sightseer commented
updated 20170925,1810

2017-09-25 12:38 UTC, sightseer commented
updated 20170925,2038

2017-09-26 06:46 UTC, Xuanwo approved these changes

2017-09-26 06:52 UTC, merged